### ISSUE TITLE
Make resource configuration interface more friendly for check step

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/concourse-vault-resource#1]
# Description/Context
This is working great so far. As we close in on a final interface for this resource I have a few thoughts on how it will work best in the context of Concourse's assumptions.

The current structure for fetching a secret looks like:
```yaml
resources:
- name: vault
  type: vault
  source:
    address: https://vault-qa.odl.mit.edu:443
    auth_engine: aws
    aws_vault_role: concourse-vault-resource

jobs:
- name: do-something
  plan:
  - get: vault
    params:
      postgres-mitxonline:
        paths:
          - readonly
        engine: database
      secret-data:
        paths:
          - dagster-http-auth-password
        engine: kv2
```

This makes it easy to fetch multiple different secrets, but makes it difficult to allow for using the `check` step to identify the proper version for KV2 secrets, or manage lease information for dynamic credentials, because there is no secret associated with the resource definition. 

# Plan/Design
To make this more native to the pipeline constructs and allow for triggering job execution via version/lease changes I propose an interface that looks like:
```yaml
resources:
- name: vault-postgres
  type: vault
  source:
    address: https://vault-qa.odl.mit.edu:443
    auth_engine: aws
    aws_vault_role: concourse-vault-resource
    mount: postgres-mitxonline
    path: readonly
    engine: database
- name: vault-secret
  type: vault
  source:
    address: https://vault-qa.odl.mit.edu:443
    auth_engine: aws
    aws_vault_role: concourse-vault-resource
    mount: secret-data
    path: dagster-http-auth-password
    engine: kv2

jobs:
- name: use-vault
  plan:
  - get: vault-postgres
  - get: vault-secret
```

This adds more boilerplate for getting multiple secrets, but it has a few benefits:
- There is only one secret per resource, which means that it's easier to manage the `check` logic to get the version information, and potentially manage lease lifecycles and refreshes
- It is more visible in the rendered pipeline via the UI how many/which secrets are required as part of the pipeline
